server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql.teaching-cloud.svc.cluster.local:3306/order_db
    username: root
    password: ${DB_PASSWORD}
  cloud:
    nacos:
      discovery:
        server-addr: nacos.teaching-cloud.svc.cluster.local:8848

seata:
  service:
    grouplist:
      default: seata-server.teaching-cloud.svc.cluster.local:8091

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
