version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos-teaching
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
